heat_template_version: 2013-05-23

description: |
  Deploys a salt-master and a number of salt-minions.
  One minion will be an haproxy node.
  One minion will be a database node.
  A variable number of minions will be web nodes each with
  apache2, php5, magento, memcached, php-apc, lsyncd, csync2, and xinetd.
  Floating ips will be assigned to the salt-master and haproxy nodes.

parameters:

  keyname:
    type: string
    label: Salt-Master Keyname.
    description: The name of the key that should be used to ssh into the Salt-Master.

  image:
    type: string
    label: Image Name
    description: Name of the existing image to use for every vm spun up by this stack. The image should have heat-config and heat-config-script baked in.

  floating-network-id:
    type: string
    label: External Network UUID
    description: UUID of the external network. The private network created by this stack will route to this network. Also, any floating ip's needed by this stack will come this network.

  minion-count:
    type: number
    default: 2
    label: Number of web servers.
    description: The number of web application servers.

  flavor:
    type: string
    label: Flavor
    description: Flavor of all vms. This may be changed in the future to allow different flavors for the different vms in this stack.
    default: m1.small

resources:

  # Random string to aid in naming things.
  stack-string:
    type: OS::Heat::RandomString
    properties:
      length: 6
      sequence: lettersdigits

  # Will be used to generate a random password
  # 32 characters long consisting of alpha numeric characters
  secret:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  # Haproxy security group
  haproxy-security:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: magento-$stackstr-secgroup
          params:
            $stackstr:
              get_attr:
                - stack-string
                - value
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80

  # Keypair for communicating between nodes within the stack.
  # Will allow minions to ssh into the master and vice versa.
  coms:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true 
      name:
        str_replace:
          template: magento-$stackstr-coms
          params:
            $stackstr:
              get_attr:
                - stack-string
                - value 

  # Private network for this stack
  net:
    type: OS::Neutron::Net

  # Private subnet for this stack
  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id:
        get_resource: net
      cidr: 10.20.20.0/24
      dns_nameservers:
        - 8.8.8.8
        - 4.2.2.2

  # Routes the private network to the external network.
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: 
          get_param: floating-network-id

  # Router interface
  interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id:
        get_resource: router
      subnet_id: 
        get_resource: subnet

  # One floating ip for the salt-master node
  master-ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 
        get_param: floating-network-id

  # One port for the salt-master node
  master-port:
    type: OS::Neutron::Port
    properties:
      network_id: 
        get_resource: net

  galera:
    type: OS::Heat::ResourceGroup
    depends_on: net
    properties:
      count: 1
      resource_def:
        type: Db::Galera
        properties:
          keyname:
            get_param: keyname
          image:
            get_param: image
          floating-network-id:
            get_param: floating-network-id
          db-username: magento-stack
          db-user-password:
            get_attr:
              - secret
              - value
          db-remotehost: '%'
          apps-network:
            get_resource: net
          database: magento
          flavor:
            get_param: flavor

  # Software configuration script for the salt-master node
  # Installs salt-master, sets permission on some personality files
  # and uses git to clone any provided state/formula repos
  config-salt-master:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: public_key
        - name: state_repos
      config: |
        #!/bin/bash
        chmod 0700 /root/.ssh/coms_rsa
        chmod 0600 /srv/pillar/magento.sls

        # Add coms from minions to master
        echo "$public_key" >> /root/.ssh/authorized_keys

        # Install git
        apt-get install -y git
            
        # Install salt master
        echo "Install Salt Master"
        curl -L http://bootstrap.saltstack.org | sh -s -- -M -N
        mkdir /srv/salt
        echo -e 'file_roots:\n  base:\n    - /srv/salt' >> /etc/salt/master

        # Clone state/formula repos in state root directory
        cd /srv/salt
        while read -r line
        do
            if [ -n "$line" ]; then
                git clone $line
            fi
        done <<< "$state_repos"

        mv /srv/salt/sync-formula /srv/salt/sync
        mv /srv/salt/magento-formula /srv/salt/magento

        # Finally - Restart salt service
        service salt-master restart

  # Software configuration for salt minion
  # Installs salt-minion, sets up authentication from minion to master,
  # and sets permissions of any personality files.
  config-salt-minion:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: public_key
        - name: master
      config: |
        #!/bin/bash
        chmod 0700 /root/.ssh/coms_rsa
            
        # Add coms from minions to master
        echo "$public_key" >> /root/.ssh/authorized_keys

        # Install salt minion
        curl -L http://bootstrap.saltstack.org | sh -s
        echo master: $master >> /etc/salt/minion

        service salt-minion restart

        ssh-keyscan -H $master >> /root/.ssh/known_hosts

        echo "Sleeping for 20s"
        sleep 20

        MASTER_PKI_PATH="/etc/salt/pki/master/minions/"
        MASTER_PKI_PATH_PRE="/etc/salt/pki/master/minions_pre/"
        MINION_PKI_PATH="/etc/salt/pki/minion/minion.pub"
        HOSTNAME=`hostname --fqdn`

        cp $MINION_PKI_PATH /root/minion_key

        scp -i /root/.ssh/coms_rsa /root/minion_key root@$master:/tmp/$HOSTNAME

        ssh -i /root/.ssh/coms_rsa root@$master "mv /tmp/$HOSTNAME $MASTER_PKI_PATH$HOSTNAME; chmod 700 $MASTER_PKI_PATH$HOSTNAME; rm $MASTER_PKI_PATH_PRE$HOSTNAME"

        service salt-minion restart
        rm /root/minion_key
        rm /root/.ssh/coms_rsa

  # Software deployment for salt-master. Deploys the salt-master software
  # configuration.
  deploy-salt-master:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        public_key:
          get_attr:
            - coms
            - public_key
        state_repos: |
          https://github.com/absalon-james/sync.git
          https://github.com/absalon-james/magento.git
      config:
        get_resource: config-salt-master
      server:
        get_resource: master

  # The salt master instance
  # Should have one floating ip
  master:
    type: OS::Nova::Server
    depends_on: interface
    properties:
      key_name:
        get_param: keyname
      image: 
        get_param: image
      flavor:
        get_param: flavor
      name:
        str_replace:
          template: magento-$stackstr-master
          params:
            $stackstr:
              get_attr:
                - stack-string
                - value
      personality:

        # Private key for ssh'ing into minions
        /root/.ssh/coms_rsa:
          get_attr:
            - coms
            - private_key

        # The top.sls file for salt states.
        # Dictates which minions get which formulas
        /srv/salt/top.sls: |
          base:
            'roles:web':
              - match: grain
              - magento.web
              - sync
            'roles:haproxy':
              - match: grain
              - magento.haproxy

        # The top.sls file for salt pillars.
        # Dictates which minions get which pillars.
        /srv/pillar/top.sls: |
          base:
            '*':
              - app
            'roles:web':
              - match: grain
              - magento

        # The app pillar. Describe interfaces and salt-mine functions.
        /srv/pillar/app.sls: |
          interfaces:
            private: eth0
            public: eth0
          mine_functions:
            network.ip_addrs: [eth0]
            network.interfaces: []
            grains.get: ['host']
          mine_interval: 1
          magento_version: 1.9.0.1
          sync:
            group: magento
            includes:
              - /var/www
            excludes:
              - /var/www/var/cache*
              - /var/www/var/report*
              - /var/www/var/log*
              - /var/www/var/session/*
              - /var/www/media/catalog/product/cache*
              - /var/www/var/locks/*
 
        # The magento.sls pillar. Describe database account info for magento
        # This file should have its permissions changed during software
        # Configuration
        /srv/pillar/magento.sls:
          str_replace:
            template: |
              magento:
                db:
                  user: magento-stack
                  password: $pw
                  write:
                    port: 13306
                  read:
                    port: 3306
                  
            params:
              $pw:
                get_attr:
                  - secret
                  - value

      # Get access from the master-port
      networks:
        - port:
            get_resource: master-port

      # Using SoftwareConfigs - This needs to be set to SOFTWARE_CONFIG
      user_data_format: SOFTWARE_CONFIG

  # Associate the master floating ip to the master port
  master-floating-ip-ass: 
    type: OS::Neutron::FloatingIPAssociation
    properties: 
      floatingip_id:
        get_resource: master-ip
      port_id:
        get_resource: master-port

  # Deploys a group of (vms + software deployment).
  # This group the varying number of web servers.
  # Each instance in this group will be an instance with salt-minion
  # installed and will have the salt role of 'web'
  minion-group-web:
    type: OS::Heat::ResourceGroup
    depends_on: deploy-salt-master
    properties:
      count:
        get_param: minion-count
      resource_def:
        type: Salt::Minion
        properties:
          flavor:
            get_param: flavor
          stack-prefix:
            str_replace:
              template: magento-$stackstr-web
              params:
                $stackstr:
                  get_attr:
                    - stack-string
                    - value
          private_key:
            get_attr:
              - coms
              - private_key
          public_key:
            get_attr:
              - coms
              - public_key
          image:
            get_param: image
          network:
            get_resource: net
          master:
            get_attr:
              - master
              - first_address
          minion-config:
            get_resource: config-salt-minion
          minion-roles: "web"

  # Floating ip for haproxy node
  minion-haproxy-ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 
        get_param: floating-network-id

  # Port for haproxy node
  minion-haproxy-port:
    type: OS::Neutron::Port
    properties:
      network_id: 
        get_resource: net
      security_groups:
        - default
        - get_resource: haproxy-security

  # haproxy minion
  minion-haproxy:
    type: OS::Nova::Server
    depends_on: interface
    properties:
      flavor:
        get_param: flavor
      image:
        get_param: image
      name:
        str_replace:
          template: magento-$stackstr-haproxy
          params:
            $stackstr:
              get_attr:
                - stack-string
                - value
      personality:

        # Private key for node to node communication
        /root/.ssh/coms_rsa:
          get_attr:
            - coms
            - private_key

        # Set the salt role to haproxy
        /etc/salt/grains: |
          roles:
            - haproxy
      
      networks:
        - port:
            get_resource: minion-haproxy-port

      # Needs to be SOFTWARE_CONFIG when using SoftwareConfigs
      user_data_format: SOFTWARE_CONFIG

  # Associate haproxy floating ip to the port
  minion-haproxy-floating-ip-ass: 
    type: OS::Neutron::FloatingIPAssociation
    properties: 
      floatingip_id:
        get_resource: minion-haproxy-ip
      port_id:
        get_resource: minion-haproxy-port

  # Deploys the salt-minion software config to the haproxy node.
  deploy-haproxy:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy-salt-master
    properties:
      input_values:
        public_key:
          get_attr:
            - coms
            - public_key
        master:
          get_attr:
            - master
            - first_address
      config:
        get_resource: config-salt-minion
      server:
        get_resource: minion-haproxy

  # SoftwareConfig that is to run on master.
  # Executes a salt state.highstate on all attached minions.
  config-deploy:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: db
        - name: haproxy
      config: |
        #!/bin/bash
        echo "    host: $db" >> /srv/pillar/magento.sls
        echo "  haproxy: {host: $haproxy}" >> /srv/pillar/magento.sls
        salt '*' saltutil.refresh_pillar
        salt '*' mine.update
        salt '*' state.highstate
        salt -G roles:web service.start lsyncd
        sudo salt --async $(sudo salt -G roles:web test.ping | head -1  | sed 's/://') cmd.run "echo 'Running fix_tables' && bash fix_tables.sh &"

  # Deploys the the deploy softwareconfig
  # All minions should be spun up and running salt-minion
  # before executing this deployment.
  deploy:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: config-deploy
      server:
        get_resource: master
      input_values:
        db:
          get_attr:
            - galera
            - haproxy-ip
            - 0
        haproxy:
          get_attr:
            - minion-haproxy-ip
            - floating_ip_address
        state_repos: |
          https://github.com/absalon-james/mysql.git
          https://github.com/absalon-james/sync.git
          https://github.com/absalon-james/magento.git

    depends_on:
      - galera
      - deploy-salt-master
      - minion-group-web
      - deploy-haproxy

outputs:
  master-ip:
    description: The salt master. SSH here first to get into the other vms.
    value: 
      get_attr:
        - master-ip
        - floating_ip_address
  
  minion-web-ips:
    value:
      get_attr:
        - minion-group-web
        - minion-ip

  minion-haproxy-ip:
    value:
      get_attr:
        - minion-haproxy-ip
        - floating_ip_address

  magento-url:
    description: How to reach your magento.
    value:
      str_replace:
        template: http://$haproxyip/
        params:
          $haproxyip:
            get_attr:
              - minion-haproxy-ip
              - floating_ip_address

  magento-db-user:
    description: The database username. (Needed to finish magento installation)
    value: 'magento-stack'

  magento-db-password:
    description: The database password. (Needed to finish magento installation)
    value:
      get_attr:
        - secret
        - value

  # Uncomment the stdout's and stderr's if problems are occuring.
  #master-stdout:
  #  value:
  #    get_attr:
  #     - deploy-salt-master
  #     - deploy_stdout
  #master-stderr:
  #  value:
  #    get_attr:
  #      - deploy-salt-master
  #      - deploy_stderr

  #minion-web-stdout:
  #  value:
  #    get_attr:
  #      - minion-group-web
  #      - minion-stdout
  #minion-web-stderr:
  #  value:
  #    get_attr:
  #      - minion-group-web
  #      - minion-stderr
